#!/usr/bin/python
import os
import sys
import optparse

import varch

def parse():
    '''
    Parse arguments
    '''
    parser = optparse.OptionParser()
    parser.add_option('-c',
            '--config',
            '--conf',
            dest='conf',
            default='/etc/varch/base.aif',
            help='The location to the Archlinux Instalation Framework file; default=/etc/varch/base.aif')
    parser.add_option('-f',
            '--format',
            dest='format',
            default='raw',
            help='The disk image format to use, raw, qcow2 or vdi; default=raw')
    parser.add_option('-s',
            '--size',
            dest='size',
            default='20G',
            help='The size of the disk image, default=20G')
    parser.add_option('-i',
            '--image',
            dest='image',
            default='arch',
            help='The location of the image after it has been created, if not supplied an extension based on the format type will be appended; default=arch')
    parser.add_option('-g',
            '--generic',
            dest='generic',
            default=False,
            action='store_true',
            help='Generate a generic virtual machine image without support for virtio block drivers')
    parser.add_option('-o',
            '--overlay',
            dest='overlay',
            default='',
            help='The directory containig files to be coppied into the virtual machine')
            
            
    options, args = parser.parse_args()

    opts = {}
    opts['conf'] = options.conf
    opts['format'] = options.format
    opts['size'] = options.size
    opts['image'] = options.image
    opts['generic'] = options.generic
    opts['overlay'] = options.overlay

    if opts['format'] == 'vdi':
        opts['generic'] = True

    return opts


if __name__ == '__main__':
    opts = parse()
    if os.getuid():
        print('Sorry, the creation of virtual machines requires root access')
        sys.exit(1)
    v_arch = varch.VArch(opts)
    v_arch.make_vm()
